# -*- coding: utf-8 -*-
"""rabota 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WsfO4sfg2fjEhWHfnoVspEhetcVqBjuj

Практическое Задание №1

**Жирный текст**, *курсив*

Список:
* Элемент 1
* Элемент 2


Нумерованный список:
1. Элемент 1
2. Элемент 2

a^2 + b^2 = c^2

![Описание](https://i.pinimg.com/236x/0e/bd/26/0ebd262c4b7f69f7ec915dbd8509328f.jpg)
"""

print("Введите ваше имя")
name=input()
print('Привет,' + name + '! Добро пожаловать в Jupiterlab')

import math

t1 = math.pi / 2

t2 = math.cos(t1) + 1j * math.sin(t1)

print(t2)

import os
with open("example.txt", "w") as f:
        f.write("Первая строка\n")
        f.write("Вторая строка\n")
with open("example.txt", "r") as f:
    content = f.read()
    print("Содержимое файла \n", content)
print("Файл существует", os.path.exists("example.txt"))
os.remove("example.txt")
print("Файл удалён")

# Commented out IPython magic to ensure Python compatibility.
# %lsmagic

# Commented out IPython magic to ensure Python compatibility.
# %time sum(range(1000000))

# Commented out IPython magic to ensure Python compatibility.
# %%timeit
# total = 0
# for i in range(1000000):
#     total += i

# Commented out IPython magic to ensure Python compatibility.
# %%writefile script.py
# 
# print("Привет, это Python-скрипт!")

# Commented out IPython magic to ensure Python compatibility.
# %ls

# Commented out IPython magic to ensure Python compatibility.
# %history

!ls

!which python

!mkdir new_folder

!rmdir new_folder

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive

from google.colab import drive

# Подключение Google Drive
drive.mount('/content/drive')

# Запись текста в файл
file_path = "/content/drive/MyDrive/my_text_file.txt"
with open(file_path, "w") as f:
    f.write("Это тестовый файл, сохраненный в Google Drive.\n")
    f.write("Вторая строка текста.")
print("Файл успешно сохранен в Google Drive.")

# Чтение файла
with open(file_path, "r") as f:
    content = f.read()
    print("Содержимое файла:\n", content)

# Создание CSV вручную
students = [
    ["Иванов И.И.", 20, "ИВТ-101"],
    ["Сидорова А.А.", 21, "ИВТ-103"],
    ["Петров П.П.", 22, "ИВТ-102"],
]
csv_path = "/content/drive/MyDrive/students.csv"
with open(csv_path, "w") as f:
    for student in students:
        f.write(",".join(map(str, student)) + "\n")
print("Файл students.csv успешно сохранен в Google Drive.")

